name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ajusta a la rama principal de tu repositorio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Reveal.js presentation
        run: npm run build # o el comando necesario para construir tu presentación

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout gh-pages
          git pull origin gh-pages
          cp -r build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
